<?php

namespace Shiptor\Bundle\FiasBundle\Repository;

/**
 * CurrentStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrentStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
