<?php

namespace Shiptor\Bundle\FiasBundle\Repository;

/**
 * EstateStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstateStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
