<?php

namespace Shiptor\Bundle\FiasBundle\Repository;

/**
 * FlatTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
