<?php
namespace Shiptor\Bundle\FiasBundle\Repository;

/**
 * UpdateListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateListRepository extends \Doctrine\ORM\EntityRepository
{
}
