<?php
namespace Shiptor\Bundle\FiasBundle\Repository;

/**
 * UpdateListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateListRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $version
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getUpdateList($version)
    {
        $qb = $this->createQueryBuilder('ul');

        if ($version) {
            $qb
                ->where('ul.versionId = :versionId')
                ->setParameter('versionId',$version);
        }

        return $qb;
    }
}
